version: '3'

networks:
  toolbox_backend:
  traefik_net:
    external: true

services:

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    environment:
        SA_PASSWORD: ${TOOLBOX_DB_SA_PASSWORD}
        ACCEPT_EULA: "Y"
    volumes:
       - ${datadir}/mssql/data:/var/opt/mssql/data
       - ${datadir}/mssql/log:/var/opt/mssql/log
       - ${datadir}/mssql/secrets:/var/opt/mssql/secrets
    networks:
      - toolbox_backend
    ports:
      - 1433:1433


  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    restart: always
    depends_on:
      - mssql
    networks:
      - toolbox_backend
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "${TOOLBOX_DB_SA_PASSWORD}" -Q "create database Keycloak"; do sleep 5; done'




  # keycloak:
  #   image: jboss/keycloak
  #   restart: always
  #   environment:
  #     - KEYCLOAK_USER=${KEYCLOAK_USER}
  #     - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
  #     - DB_VENDOR=mssql
  #     - DB_USER=${KEYCLOAK_DB_USER}
  #     - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
  #     - DB_ADDR=${KEYCLOAK_DB_SERVER}
  #     - DB_DATABASE=${KEYCLOAK_DB_NAME}
  #     - PROXY_ADDRESS_FORWARDING=true
  #   labels:
  #     - traefik.frontend.rule=Host:login.${TOOLBOX_BASE_URL}
  #     - traefik.docker.network=traefik_net
  #     - traefik.enable=true
  #     - traefik.port=8080
  #     # - traefik.port=8443
  #     # - traefik.protocol=https
  #   networks:
  #     - toolbox_backend
  #     - traefik_net
  #   depends_on:
  #     - mssql
  #     - mssqlscripts
